# Generated by Django 3.2.16 on 2022-12-13 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taskname', models.TextField(max_length=255)),
                ('Taskdate', models.DateTimeField(blank=True, null=True)),
                ('Taskuser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='app1.user')),
            ],
        ),
    ]
