# Generated by Django 3.2.16 on 2022-12-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_user_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='Taskuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointments', to='app1.user'),
        ),
    ]
