# Generated by Django 3.2.16 on 2022-12-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_appointments_taskuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ManyToManyField(related_name='movies', to='app1.User'),
        ),
    ]
